//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lineaBlanca
{
    using System;
    using System.Collections.Generic;
    
    public partial class credito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public credito()
        {
            this.productoes = new HashSet<producto>();
            this.pagoes = new HashSet<pago>();
        }
    
        public int id_credito { get; set; }
        public int id_usuario { get; set; }
        public int id_cliente { get; set; }
        public decimal interes { get; set; }
        public Nullable<System.DateTime> fecha_compra { get; set; }
        public decimal total { get; set; }
        public Nullable<decimal> cuota { get; set; }
        public Nullable<int> cantidad_cuotas { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public string estado { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> productoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago> pagoes { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
