//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lineaBlanca
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pago()
        {
            this.cuota = new HashSet<cuota>();
        }
    
        public int id_pago { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public decimal monto { get; set; }
        public int id_credito { get; set; }
        public decimal total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuota> cuota { get; set; }
    }
}
