//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lineaBlanca
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        public int id_pago { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public decimal monto { get; set; }
        public Nullable<System.DateTime> fecha_limite { get; set; }
        public Nullable<decimal> mora { get; set; }
        public string estado { get; set; }
        public int id_credito { get; set; }
    
        public virtual credito credito { get; set; }
    }
}
