//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lineaBlanca
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        public int id_pago { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public decimal monto { get; set; }
        public Nullable<System.DateTime> fecha_limite { get; set; }
        public Nullable<decimal> mora { get; set; }
        public string estado { get; set; }
        public int id_credito { get; set; }
    
        public virtual credito credito { get; set; }
    }
}
